/**
 * @file Main_N64.cpp
 * @brief N64 entry point — boots libdragon, the engine, and runs the loop.
 *
 * Mirrors Standalone/Source/Main.cpp (desktop) + Main_PSP.cpp (handheld).
 * libdragon-specific boot:
 *
 *   - debug_init_isviewer() routes printf/debugf to ISViewer (Mupen, ares)
 *     so the host log window captures engine logs.
 *   - debug_init_usb() routes the same output to UART on flashcarts that
 *     expose USB (EverDrive 64, 64Drive) so real-hw debugging works.
 *   - display_init() configures the framebuffer. 320×240 RGBA16 with no AA,
 *     gamma-corrected, double-buffered — the standard homebrew preset.
 *   - dfs_init() mounts the DragonFS image appended to the ROM (the addon's
 *     Makefile stage: target appends a `.dfs` at offset 1 MB when present).
 *   - controller_init() enables controller polling — Phase 2 wires it to
 *     the engine; Phase 1 just turns it on.
 *
 * The engine's int main is gated out when POLYPHASE_PLATFORM_ADDON is
 * defined, so our main below is the sole entry.
 */

#if defined(POLYPHASE_PLATFORM_ADDON)

#include <libdragon.h>

#include <cstdio>
#include <cstring>

#include "Engine.h"
#include "EmbeddedFile.h"
#include "Log.h"

// Embedded-scripts table generated by the editor's packager. Same wiring
// as the PSP and desktop ports — N64's DragonFS could in theory load Lua
// scripts from `rom:/Scripts/` at runtime, but the embed path is simpler
// and saves the per-load DMA latency.
extern uint32_t gNumEmbeddedScripts;
extern EmbeddedFile gEmbeddedScripts[];

// -------------------------------------------------------------------------
// Oct* hooks — minimal stubs.
// -------------------------------------------------------------------------

void OctPreInitialize(EngineConfig& config)
{
    GetEngineState()->mStandalone = true;

    // Fix the logical viewport at 320x240 (NTSC). PostPackage rewrites
    // Config.ini to the same values, but we set them here too so the
    // first-frame layout pass uses the right dims even if Config.ini was
    // not patched.
    config.mWindowWidth  = 320;
    config.mWindowHeight = 240;

    config.mEmbeddedScriptCount = gNumEmbeddedScripts;
    config.mEmbeddedScripts     = gEmbeddedScripts;
}

void OctPostInitialize()
{
    // Defends against ReadEngineConfig() clobbering OctPreInitialize's
    // window dims with whatever the project authored for desktop (typically
    // 1280×720). Mirrors PSP's belt-and-suspenders pattern.
    const uint32_t beforeW = GetEngineState()->mWindowWidth;
    const uint32_t beforeH = GetEngineState()->mWindowHeight;
    GetEngineState()->mWindowWidth  = 320;
    GetEngineState()->mWindowHeight = 240;

#if defined(N64_EXPANSION_PAK)
    GetEngineState()->mSystem.mExpansionPak = true;
#else
    // Probe at runtime — `get_memory_size()` returns 4 or 8 MB. If 8 MB,
    // the user has an Expansion Pak; opportunistically use it even if the
    // build wasn't compiled with -DN64_EXPANSION_PAK=1.
    GetEngineState()->mSystem.mExpansionPak = (get_memory_size() >= 8 * 1024 * 1024);
#endif

    debugf("[N64] OctPostInitialize: window %ux%u -> 320x240, expansionPak=%d\n",
             (unsigned)beforeW, (unsigned)beforeH,
             (int)GetEngineState()->mSystem.mExpansionPak);
}

void OctPreUpdate() {}
void OctPostUpdate() {}
void OctPreShutdown() {}
void OctPostShutdown() {}

// -------------------------------------------------------------------------
// Engine entry. GameMain bundles the standard boot sequence; we just call
// it after libdragon's services are up.
// -------------------------------------------------------------------------

extern void GameMain(int32_t argc, char** argv);

int main(void)
{
    // Boot diagnostics first — both sinks fail-safe: ISViewer is no-op when
    // not running under Mupen/ares; usb logging is no-op when no flashcart
    // is plugged in. Either way, debugf() in subsequent code is safe.
    //
    // NB: do NOT prefix libdragon API calls with `::`. Many of these "func-
    // tions" (debug_init_isviewer, debug_init_usb, display_init, dfs_init,
    // controller_init, etc.) are object-like macros that expand to a call
    // through a different identifier — prefixing with `::` glues a `::` to
    // the macro body and produces invalid token sequences like
    // `::debug_init(DEBUG_FEATURE_LOG_ISVIEWER)()`. C-style unqualified
    // calls work because the macros expand fully without scope conflicts.
    debug_init_isviewer();
    debug_init_usblog();  // libdragon's USB-debug sink — `debug_init_usb` is the older name.
    debugf("[1] Polyphase N64 boot start\n");

    // Display: 320x240 RGBA16, double-buffered, no AA. RGBA16 is the cheapest
    // mode that gives reasonable color depth on N64; RGBA32 doubles VRAM cost.
    display_init(RESOLUTION_320x240, DEPTH_16_BPP, 2, GAMMA_NONE, FILTERS_RESAMPLE);
    debugf("[2] Display initialised\n");

    // DragonFS — mount the .dfs image that the addon's stage: target
    // appends to the ROM at offset 1MB. If no .dfs is present (Phase 1
    // builds without baked assets), dfs_init returns an error that we
    // log and continue — the engine then loads only embedded scripts.
    const int dfsRc = dfs_init(DFS_DEFAULT_LOCATION);
    if (dfsRc == DFS_ESUCCESS)
    {
        debugf("[3] DragonFS mounted\n");
    }
    else
    {
        debugf("[3] DragonFS not present (rc=%d) - embedded scripts only\n", dfsRc);
    }

    // Controllers — libdragon polls in interrupt context; Input_N64 just
    // reads the cached state.
    controller_init();
    debugf("[4] Controllers initialised\n");

    // Timer subsystem powers wait_ms / get_ticks() — needed by SYS_Sleep
    // and SYS_GetTimeMicroseconds.
    timer_init();
    debugf("[5] Timer subsystem initialised\n");

    debugf("[6] About to call GameMain()\n");
    char  arg0[] = "polyphase";
    char* argv[] = { arg0, nullptr };
    GameMain(1, argv);
    debugf("[7] GameMain() returned cleanly\n");

    display_close();
    timer_close();

    // N64 has no clean exit — main loop in GameMain runs forever in
    // homebrew. If GameMain returns we just spin. (Real hardware: the
    // Reset button hard-resets the console.)
    while (1) { wait_ms(1000); }

    return 0;
}

#endif // POLYPHASE_PLATFORM_ADDON
